# Generated by Django 5.2 on 2025-04-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('balance-rr', 'Round Robin'), ('active-backup', 'Active Backup'), ('balance-xor', 'XOR'), ('broadcast', 'Broadcast'), ('802.3ad', 'LACP'), ('balance-tlb', 'Adaptive Transmit Load Balancing'), ('balance-alb', 'Adaptive Load Balancing')], default='balance-rr', max_length=20)),
                ('slaves', models.CharField(max_length=255)),
                ('status', models.CharField(default='down', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BondStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmit', models.BigIntegerField(default=0)),
                ('receive', models.BigIntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('active_slave', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.bondinterface')),
            ],
        ),
    ]
