# Generated by Django 5.2 on 2025-06-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lte_type', models.CharField(max_length=10)),
                ('packet_loss', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'lte_type'], name='network_pac_timesta_fe3db5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PacketLossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lte_type', models.CharField(blank=True, max_length=10, null=True)),
                ('packet_loss', models.FloatField()),
                ('latency', models.CharField(max_length=255)),
                ('jitter', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'lte_type'], name='network_pac_timesta_769c8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictedParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lte_type', models.CharField(max_length=10)),
                ('predicted_rsrp', models.FloatField()),
                ('predicted_rsrq', models.FloatField()),
                ('predicted_sinr', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'lte_type'], name='network_pre_timesta_8a86d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='RFParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lte_type', models.CharField(max_length=10)),
                ('rsrp', models.FloatField()),
                ('rsrq', models.FloatField()),
                ('rssi', models.FloatField()),
                ('sinr', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'lte_type'], name='network_rfp_timesta_32ad28_idx')],
            },
        ),
    ]
