# Generated by Django 5.2 on 2025-06-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.CharField(max_length=45)),
                ('destination_ip', models.CharField(max_length=45)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=50)),
                ('ndpi_protocol', models.CharField(blank=True, max_length=50)),
                ('risks', models.JSONField(blank=True, null=True)),
                ('details', models.JSONField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['first_seen'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_retention_minutes', models.PositiveIntegerField(default=60, help_text='Retention period for general logs in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='SevereFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_seen', models.DateTimeField()),
                ('source_ip', models.CharField(max_length=45)),
                ('destination_ip', models.CharField(max_length=45)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=50)),
                ('ndpi_protocol', models.CharField(blank=True, max_length=50)),
                ('risks', models.JSONField()),
                ('details', models.JSONField()),
            ],
        ),
    ]
