Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.ssh.forward_x11 = true

  # Forward ports for application
  config.vm.network "forwarded_port", guest: 4200, host: 8400, host_ip: "221.171.85.50"
  config.vm.network "forwarded_port", guest: 8001, host: 8001, host_ip: "221.171.85.50"

  # Provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "Sdwan"
    vb.memory = "4096"
  end

  # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    # Update package list
    apt-get update

    # Install dependencies for various tools
    apt-get install -y libnfnetlink0 libnetfilter-log1 libnetfilter-conntrack3 libncurses5 libncurses6 build-essential git gettext flex bison libtool autoconf automake pkg-config libpcap-dev libjson-c-dev libnuma-dev libpcre2-dev libmaxminddb-dev librrd-dev snmp snmpd python3 python3-venv python3-pip

    # Install additional packages for python-ldap
    apt-get install -y libldap2-dev libsasl2-dev python3-dev libssl-dev

    # Install and configure nDPI
    wget https://github.com/ntop/nDPI/archive/refs/tags/4.12.tar.gz
    tar -xvzf 4.12.tar.gz
    cd nDPI-4.12
    ./autogen.sh
    make
    make check
    sudo make install

    # Install and configure FRR (Free Range Routing)
    sudo apt-get install -y frr

    # Install SNMP
    sudo apt-get install -y snmp snmpd

    # Install vuurmuur (Firewall tool)
    wget https://github.com/inliniac/vuurmuur/releases/download/0.8.2/vuurmuur_0.8.2-1bookworm1_amd64.deb
    sudo dpkg -i vuurmuur_0.8.2-1bookworm1_amd64.deb
    sudo apt-get install -f # Fix any dependency issues

    # Clone the SD-WAN project repository
    cd /home/vagrant/sdwan_project
    if [ ! -d "sdwan_project" ]; then
      git clone http://oauth2:glpat-_zx1wET_D1R8fW9LKvWr@221.171.86.116:32769/divyanshi_tripathi/sdwan_project.git
    fi
    cd sdwan_project/
    python3 -m venv venv
    source venv/bin/activate

    #source venv/bin/activate
    # Install Python virtual environment and activate it
    #python3 -m venv /home/vagrant/sdwan_project/venv
    #source /home/vagrant/sdwan_project/venv/bin/activate

    # Install Python dependencies
    pip install --upgrade pip
    pip install django python-ldap django-auth-ldap


    # Run the Django development server
    python3 manage.py runserver 0.0.0.0:8001
  SHELL
end
