# Generated by Django 5.1.5 on 2025-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lte_type', models.CharField(max_length=10)),
                ('packet_loss', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'lte_type'], name='network_mon_timesta_501439_idx')],
                'unique_together': {('timestamp', 'lte_type')},
            },
        ),
        migrations.CreateModel(
            name='PredictedParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lte_type', models.CharField(max_length=10)),
                ('predicted_rsrp', models.FloatField()),
                ('predicted_rsrq', models.FloatField()),
                ('predicted_sinr', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'lte_type'], name='network_mon_timesta_af71fc_idx')],
                'unique_together': {('timestamp', 'lte_type')},
            },
        ),
        migrations.CreateModel(
            name='RFParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lte_type', models.CharField(max_length=10)),
                ('rsrp', models.FloatField()),
                ('rsrq', models.FloatField()),
                ('rssi', models.FloatField()),
                ('sinr', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'lte_type'], name='network_mon_timesta_3e262e_idx')],
                'unique_together': {('timestamp', 'lte_type')},
            },
        ),
    ]
