# Generated by Django 5.1.5 on 2025-01-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packetloss',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='predictedparameters',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rfparameters',
            unique_together=set(),
        ),
    ]
