# Generated by Django 5.1.5 on 2025-02-25 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitoring', '0002_alter_packetloss_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketLossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('packet_loss', models.FloatField()),
                ('latency', models.FloatField(blank=True, null=True)),
                ('jitter', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
