# Generated by Django 5.1.5 on 2025-03-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitoring', '0003_packetlossrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetlossrecord',
            name='lte_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='packetlossrecord',
            name='jitter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='packetlossrecord',
            name='latency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='packetlossrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='packetlossrecord',
            index=models.Index(fields=['timestamp', 'lte_type'], name='network_mon_timesta_157a27_idx'),
        ),
    ]
