# Generated by Django 4.2.18 on 2025-04-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetanalysis',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='packetanalysis',
            name='severity',
        ),
    ]
