# Generated by Django 4.2.18 on 2025-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_analysis', '0002_remove_packetanalysis_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packetanalysis',
            options={'ordering': ['-first_seen']},
        ),
        migrations.RemoveField(
            model_name='packetanalysis',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='packetanalysis',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packetanalysis',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
