# Generated by Django 4.2.18 on 2025-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_analysis', '0003_alter_packetanalysis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_retention_minutes', models.PositiveIntegerField(default=60, help_text='Retention period for general logs in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='SevereFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_seen', models.DateTimeField()),
                ('source_ip', models.CharField(max_length=45)),
                ('destination_ip', models.CharField(max_length=45)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=50)),
                ('ndpi_protocol', models.CharField(blank=True, max_length=50)),
                ('risks', models.JSONField()),
                ('details', models.JSONField()),
            ],
        ),
    ]
