# Generated by Django 4.2.18 on 2025-04-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_analysis', '0004_analysislog_settings_severeflowlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisLog',
        ),
        migrations.AlterModelOptions(
            name='packetanalysis',
            options={'ordering': ['first_seen']},
        ),
    ]
