# Generated by Django 5.1.4 on 2024-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_uri', models.URLField(verbose_name='LDAP Server URI')),
                ('bind_dn', models.CharField(max_length=255, verbose_name='Bind DN')),
                ('bind_password', models.CharField(max_length=255, verbose_name='Bind Password')),
                ('user_search_base', models.CharField(max_length=255, verbose_name='User Search Base')),
            ],
            options={
                'verbose_name': 'LDAP Configuration',
                'verbose_name_plural': 'LDAP Configurations',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
